print("%s" % "    *    ")
print("%s" % "   ***   ")
print("%s" % "  *****  ")
print("%s" % " ******* ")
print("%s" % "*********")
print("%s" % " ******* ")
print("%s" % "  *****  ")
print("%s" % "   ***   ")
print("%s" % "    *    ")

print("감사합니다.")